# Generated by Django 5.1.6 on 2025-03-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='active',
            new_name='is_active',
        ),
    ]
