# Generated by Django 5.1.6 on 2025-03-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_rename_active_college_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='is_active',
            new_name='active',
        ),
    ]
