# Generated by Django 5.1.6 on 2025-03-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[(0, 'Present'), (1, 'Absent'), (2, 'Pending')], default='Pending', max_length=10),
        ),
    ]
