# Generated by Django 5.1.6 on 2025-03-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0006_remove_student_attendence_student_attendance_and_more'),
        ('gate', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('0', 'Present'), ('1', 'Absent'), ('2', 'Pending')], default='2', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='collegeApp.student'),
        ),
    ]
