# Generated by Django 5.1.6 on 2025-03-01 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0007_alter_student_id'),
        ('gate', '0004_remove_attendance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='collegeApp.student'),
        ),
    ]
