# Generated by Django 5.1.6 on 2025-03-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0005_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[(0, 'Present'), (1, 'Absent'), (2, 'Pending')], default=2, max_length=10),
        ),
    ]
