# Generated by Django 5.1.6 on 2025-03-01 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0001_initial'),
        ('collegeApp', '0001_initial'),
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='gate.attendance'),
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.college'),
        ),
    ]
