# Generated by Django 5.1.6 on 2025-02-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
