# Generated by Django 5.1.6 on 2025-02-24 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0002_alter_visitor_college_name'),
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='attendence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gate.attendance'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
