# Generated by Django 5.1.6 on 2025-03-01 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0004_alter_student_college_id_card'),
        ('gate', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendence',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='gate.attendance'),
        ),
    ]
