# Generated by Django 5.1.6 on 2025-03-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0005_alter_student_attendence'),
        ('gate', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendence',
        ),
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='gate.attendance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='approval',
            field=models.IntegerField(choices=[(0, 'Rejected'), (1, 'Accepted'), (2, 'Pending')], default=2),
        ),
    ]
