# Generated by Django 5.1.6 on 2025-03-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0007_alter_student_id'),
        ('gate', '0006_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='gate.attendance'),
        ),
    ]
