# Generated by Django 5.1.6 on 2025-03-02 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0008_alter_student_attendance'),
        ('gate', '0007_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='gate.attendance'),
        ),
    ]
