# Generated by Django 5.1.6 on 2025-03-01 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HomepageApp', '0001_initial'),
        ('collegeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='collegeApp.student'),
        ),
    ]
